version: '3'

services:
  app:
    container_name: vsm-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      AUTH_TOKEN_LIFETIME: ${AUTH_TOKEN_LIFETIME}
      MAX_GAME_ROUNDS: ${MAX_GAME_ROUNDS}
      ROUND_DURATION: ${ROUND_DURATION}
      CACHE_TIME: ${CACHE_TIME}
    command: ['node', 'dist/app.js']
    ports:
      - '8080:8080'
    volumes:
      - .:/app
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
